### PR TITLE
Feat: add optional parameter to define custom csv table, apply styles, and replace `os` with `pathlib`

### PR DESCRIPTION
**Pull request by matinnuhamunada**
This PR adds:
- Enforce style using [pre-commits](https://pre-commit.com/)
- Add optional parameters: custom table location
- Add optional parameters: direct logging to stderr
- Improve CLI description
- Add version information
- Add tests

### CODE REVIEW

**Comment by matinnuhamunada** [comment]
Hi @anpanche, what should be the better description for path1 and path2?
```
$ Alleleome --help

usage: Alleleome [-h] [--path1 PATH1] [--path2 PATH2] [--table TABLE] [--log_to_terminal]

Alleleome - Explore and analyze natural sequence variations within the Open Reading Frames (ORFs) of alleles of core genes in a species pan-genome.

options:
  -h, --help         show this help message and exit
  --path1 PATH1      Path argument 1
  --path2 PATH2      Path argument 2
  --table TABLE      Path to a custom CSV pangene summary table. If not provided, a default table will be used.
  --log_to_terminal  Log message will be printed to the terminal instead of a file.
  --version          show program's version number and exit
```

**Comment by anpanche** [comment]
> Hi @anpanche, what should be the better description for path1 and path2?
> 
> ```
> $ Alleleome --help
> 
> usage: Alleleome [-h] [--path1 PATH1] [--path2 PATH2] [--table TABLE] [--log_to_terminal]
> 
> Alleleome - Explore and analyze natural sequence variations within the Open Reading Frames (ORFs) of alleles of core genes in a species pan-genome.
> 
> options:
>   -h, --help         show this help message and exit
>   --path1 PATH1      Path argument 1
>   --path2 PATH2      Path argument 2
>   --table TABLE      Path to a custom CSV pangene summary table. If not provided, a default table will be used.
>   --log_to_terminal  Log message will be printed to the terminal instead of a file.
>   --version          show program's version number and exit
> ```

path1 -- path to pangenome_alignments directory
path2 -- path to alleleome directory

**Comment by matinnuhamunada** [comment]
does path to alleleome directory means the output?

**Comment by anpanche** [comment]
> > Hi @anpanche, what should be the better description for path1 and path2?
> > ```
> > $ Alleleome --help
> > 
> > usage: Alleleome [-h] [--path1 PATH1] [--path2 PATH2] [--table TABLE] [--log_to_terminal]
> > 
> > Alleleome - Explore and analyze natural sequence variations within the Open Reading Frames (ORFs) of alleles of core genes in a species pan-genome.
> > 
> > options:
> >   -h, --help         show this help message and exit
> >   --path1 PATH1      Path argument 1
> >   --path2 PATH2      Path argument 2
> >   --table TABLE      Path to a custom CSV pangene summary table. If not provided, a default table will be used.
> >   --log_to_terminal  Log message will be printed to the terminal instead of a file.
> >   --version          show program's version number and exit
> > ```
> 
> path1 -- path to pangenome_alignments directory path2 -- path to alleleome directory

One more suggestion here. The pangene summary table that will be created from roary if we could save it in alleleome directory , it will be better for further processing. My package saves all the major outputs to alleleome directory.

**Comment by matinnuhamunada** [comment]
I actually still have problems installing ncbi blast and mafft using the command you provided. Does the setup.py run automatically with pip install? @anpanche

**Comment by anpanche** [comment]
> I actually still have problems installing ncbi blast and mafft using the command you provided. Does the setup.py run automatically with pip install? @anpanche

Yes, the setup automatically installs blast and mafft. You need to install git lfs . After it , it will be automatically installed. I have added the steps to readme.

**Comment by anpanche** [comment]
> does path to alleleome directory means the output?

I would say one of the paths to output.

**Comment by matinnuhamunada** [comment]
I think I'm ready to merge. Can you merge re-base? @anpanche

**Comment by matinnuhamunada** [comment]
Does this output looks right to you?

```bash
Alleleome/sample_data/
└── Oenococcus_oeni
    ├── alleleome
    │   ├── Final_nuc_genes_present_in_above_5_percent_of_strains.csv
    │   ├── Genes_nuc_length_number_of_strains.csv
    │   ├── Genes_nuc_length_of_alleles.csv
    │   ├── core_alleles_with_length_less_than_2std_less_than_mean_length.csv
    │   ├── core_nuc_alleles_with_locus_mean_std.csv
    │   ├── core_nuc_alleles_with_mean_std.csv
    │   ├── df_pangene_summary_v2.csv
    │   ├── pan_amino_acid_vars_df.csv
    │   └── pan_core_gene_syno_non_syno_df.csv
    └── pangenome_alignments
        ├── expZ
        │   ├── input
        │   │   ├── amino_acid_consensus_expZ.faa
        │   │   ├── nucleotide_consensus_expZ.fna
        │   │   ├── pan_genes.faa
        │   │   ├── pan_genes.fna
        │   │   ├── pangenes.faa
        │   │   └── pangenes.fna
        │   └── output
        │       ├── amino_acid_blast_out_expZ.xml
        │       ├── mafft_amino_acid_expZ.fasta
        │       ├── mafft_nucleotide_expZ.fasta
        │       └── nucleotide_blast_out_expZ.xml
        ├── group_1084
        │   ├── input
        │   │   ├── amino_acid_consensus_group_1084.faa
        │   │   ├── nucleotide_consensus_group_1084.fna
        │   │   ├── pan_genes.faa
        │   │   ├── pan_genes.fna
        │   │   ├── pangenes.faa
        │   │   └── pangenes.fna
        │   └── output
        │       ├── amino_acid_blast_out_group_1084.xml
        │       ├── mafft_amino_acid_group_1084.fasta
        │       ├── mafft_nucleotide_group_1084.fasta
        │       └── nucleotide_blast_out_group_1084.xml
        ├── group_1085
        │   ├── input
        │   │   ├── amino_acid_consensus_group_1085.faa
        │   │   ├── nucleotide_consensus_group_1085.fna
        │   │   ├── pan_genes.faa
        │   │   ├── pan_genes.fna
        │   │   ├── pangenes.faa
        │   │   └── pangenes.fna
        │   └── output
        │       ├── amino_acid_blast_out_group_1085.xml
        │       ├── mafft_amino_acid_group_1085.fasta
        │       ├── mafft_nucleotide_group_1085.fasta
        │       └── nucleotide_blast_out_group_1085.xml
        ├── group_1101
        │   ├── input
        │   │   ├── amino_acid_consensus_group_1101.faa
        │   │   ├── nucleotide_consensus_group_1101.fna
        │   │   ├── pan_genes.faa
        │   │   ├── pan_genes.fna
        │   │   ├── pangenes.faa
        │   │   └── pangenes.fna
        │   └── output
        │       ├── amino_acid_blast_out_group_1101.xml
        │       ├── mafft_amino_acid_group_1101.fasta
        │       ├── mafft_nucleotide_group_1101.fasta
        │       └── nucleotide_blast_out_group_1101.xml
        ├── group_1167
        │   ├── input
        │   │   ├── amino_acid_consensus_group_1167.faa
        │   │   ├── nucleotide_consensus_group_1167.fna
        │   │   ├── pan_genes.faa
        │   │   ├── pan_genes.fna
        │   │   ├── pangenes.faa
        │   │   └── pangenes.fna
        │   └── output
        │       ├── amino_acid_blast_out_group_1167.xml
        │       ├── mafft_amino_acid_group_1167.fasta
        │       ├── mafft_nucleotide_group_1167.fasta
        │       └── nucleotide_blast_out_group_1167.xml
        ├── group_1597
        │   └── input
        │       ├── pangenes.faa
        │       └── pangenes.fna
        ├── group_1599
        │   └── input
        │       ├── pangenes.faa
        │       └── pangenes.fna
        ├── group_1610
        │   └── input
        │       ├── pangenes.faa
        │       └── pangenes.fna
        ├── group_1649
        │   └── input
        │       ├── pangenes.faa
        │       └── pangenes.fna
        └── group_1666
            └── input
                ├── pangenes.faa
                └── pangenes.fna
```

**Comment by anpanche** [comment]
> Does this output looks right to you?
> 
> ```shell
> Alleleome/sample_data/
> └── Oenococcus_oeni
>     ├── alleleome
>     │   ├── Final_nuc_genes_present_in_above_5_percent_of_strains.csv
>     │   ├── Genes_nuc_length_number_of_strains.csv
>     │   ├── Genes_nuc_length_of_alleles.csv
>     │   ├── core_alleles_with_length_less_than_2std_less_than_mean_length.csv
>     │   ├── core_nuc_alleles_with_locus_mean_std.csv
>     │   ├── core_nuc_alleles_with_mean_std.csv
>     │   ├── df_pangene_summary_v2.csv
>     │   ├── pan_amino_acid_vars_df.csv
>     │   └── pan_core_gene_syno_non_syno_df.csv
>     └── pangenome_alignments
>         ├── expZ
>         │   ├── input
>         │   │   ├── amino_acid_consensus_expZ.faa
>         │   │   ├── nucleotide_consensus_expZ.fna
>         │   │   ├── pan_genes.faa
>         │   │   ├── pan_genes.fna
>         │   │   ├── pangenes.faa
>         │   │   └── pangenes.fna
>         │   └── output
>         │       ├── amino_acid_blast_out_expZ.xml
>         │       ├── mafft_amino_acid_expZ.fasta
>         │       ├── mafft_nucleotide_expZ.fasta
>         │       └── nucleotide_blast_out_expZ.xml
>         ├── group_1084
>         │   ├── input
>         │   │   ├── amino_acid_consensus_group_1084.faa
>         │   │   ├── nucleotide_consensus_group_1084.fna
>         │   │   ├── pan_genes.faa
>         │   │   ├── pan_genes.fna
>         │   │   ├── pangenes.faa
>         │   │   └── pangenes.fna
>         │   └── output
>         │       ├── amino_acid_blast_out_group_1084.xml
>         │       ├── mafft_amino_acid_group_1084.fasta
>         │       ├── mafft_nucleotide_group_1084.fasta
>         │       └── nucleotide_blast_out_group_1084.xml
>         ├── group_1085
>         │   ├── input
>         │   │   ├── amino_acid_consensus_group_1085.faa
>         │   │   ├── nucleotide_consensus_group_1085.fna
>         │   │   ├── pan_genes.faa
>         │   │   ├── pan_genes.fna
>         │   │   ├── pangenes.faa
>         │   │   └── pangenes.fna
>         │   └── output
>         │       ├── amino_acid_blast_out_group_1085.xml
>         │       ├── mafft_amino_acid_group_1085.fasta
>         │       ├── mafft_nucleotide_group_1085.fasta
>         │       └── nucleotide_blast_out_group_1085.xml
>         ├── group_1101
>         │   ├── input
>         │   │   ├── amino_acid_consensus_group_1101.faa
>         │   │   ├── nucleotide_consensus_group_1101.fna
>         │   │   ├── pan_genes.faa
>         │   │   ├── pan_genes.fna
>         │   │   ├── pangenes.faa
>         │   │   └── pangenes.fna
>         │   └── output
>         │       ├── amino_acid_blast_out_group_1101.xml
>         │       ├── mafft_amino_acid_group_1101.fasta
>         │       ├── mafft_nucleotide_group_1101.fasta
>         │       └── nucleotide_blast_out_group_1101.xml
>         ├── group_1167
>         │   ├── input
>         │   │   ├── amino_acid_consensus_group_1167.faa
>         │   │   ├── nucleotide_consensus_group_1167.fna
>         │   │   ├── pan_genes.faa
>         │   │   ├── pan_genes.fna
>         │   │   ├── pangenes.faa
>         │   │   └── pangenes.fna
>         │   └── output
>         │       ├── amino_acid_blast_out_group_1167.xml
>         │       ├── mafft_amino_acid_group_1167.fasta
>         │       ├── mafft_nucleotide_group_1167.fasta
>         │       └── nucleotide_blast_out_group_1167.xml
>         ├── group_1597
>         │   └── input
>         │       ├── pangenes.faa
>         │       └── pangenes.fna
>         ├── group_1599
>         │   └── input
>         │       ├── pangenes.faa
>         │       └── pangenes.fna
>         ├── group_1610
>         │   └── input
>         │       ├── pangenes.faa
>         │       └── pangenes.fna
>         ├── group_1649
>         │   └── input
>         │       ├── pangenes.faa
>         │       └── pangenes.fna
>         └── group_1666
>             └── input
>                 ├── pangenes.faa
>                 └── pangenes.fna
> ```

Yes, Perfect.

**Pull request merged**
